---
services:
  enshrouded:
    build:
      context: .
      dockerfile: Dockerfile.proton
      args:
        PROTON_VERSION: GE-Proton10-32    # Use only if dockerfile is set to Dockerfile.proton
        #WINE_BRANCH: stable              # Use only if dockerfile is set to Dockerfile.wine
    image: indifferentbroccoli/enshrouded-server-docker
    restart: unless-stopped
    container_name: enshrouded
    stop_grace_period: 30s
    ports:
      - 15636:15636/udp
      - 15637:15637/udp
    env_file:
      - .env.example
    volumes:
      - ./server-files:/opt/enshrouded
      - ./server-data:/opt/enshrouded-saves
