---
services:
  enshrouded:
    image: indifferentbroccoli/enshrouded-server-docker
    restart: unless-stopped
    container_name: enshrouded
    stop_grace_period: 30s
    ports:
      - 15636:15636/udp
      - 15637:15637/udp
    env_file:
      - .env
    volumes:
      - ./server-files:/home/steam/enshrouded
